volumes:
  postgres-data:
  redis-data:

services:
  auth-service:
    container_name: auth_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    command: >
      sh -c "
      poetry run alembic upgrade head && 
      poetry run python ./src/main.py"
    depends_on:
      - database
      - redis

  database:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"

  redis:
    container_name: redis_container
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
